### PR TITLE
OSV3 Class

### PR DESCRIPTION
**Pull request by renzo38**
Hello,

The THGR810 was in fact a sensor V3 (I did not see it the first time). So, I created a SensorV3 class to handle future sensors.

### CODE REVIEW

**Comment by 1000io** [comment]
Hi! @renzo38 

Sorry but I haven't got time to test it. Have you do that? 

Thanks!

**Comment by renzo38** [comment]
Hello,

Since this pull request I bought a THGR810, installed it and found a problem. I have to make another pull request with the new file. I gather temperature and humidity every 5 minutes since 1 month, so I believe it is working now ;-) I will create the pull request tomorrow ?

**Comment by renzo38** [comment]
Hello,

You can merge.

**Comment by 1000io** [comment]
Thanks @renzo38

**Pull request merged**
